- name: Auth Service Setup
  hosts: all
  become: yes
  tasks:
    - name: Create appuser
      ansible.builtin.user:
        name: appuser
        system: yes
        shell: /bin/false

    - name: Create /app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Install Golang
      ansible.builtin.dnf:
        name: golang
        state: present

    - name: Copy service file
      ansible.builtin.copy:
        src: auth-service.service
        dest: /etc/systemd/system/auth-service.service

    - name: Download and extract application
      ansible.builtin.unarchive:
        src: https://raw.githubusercontent.com/raghudevopsb88/wealth-project/main/artifacts/auth-service.tar.gz
        dest: /app
        remote_src: yes

    - name: Build application
      ansible.builtin.shell: CGO_ENABLED=0 go build -o auth-service ./cmd/server
      args:
        chdir: /app

    - name: Set ownership
      ansible.builtin.file:
        path: /app
        owner: appuser
        group: appuser
        recurse: yes
        mode: 'o-rwx'

    - name: Start auth-service
      ansible.builtin.systemd_service:
        name: auth-service
        daemon_reload: yes
        enabled: yes
        state: restarted
