- name: Frontend Setup
  hosts: all
  become: yes
  tasks:
    - name: Install NodeJS repo files
      ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_22.x | bash -

    - name: Install nginx & NodeJS
      ansible.builtin.dnf:
        name:
          - '@nginx:1.26'
          - nodejs
        state: present

    - name: Update Nginx Config
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Remove nginx default
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: Download and extract frontend
      ansible.builtin.unarchive:
        src: https://raw.githubusercontent.com/raghudevopsb88/wealth-project/main/artifacts/frontend.tar.gz
        dest: /usr/share/nginx
        remote_src: yes

    - name: Build frontend
      ansible.builtin.shell: npm ci ; npm run build ; mv dist html
      args:
        chdir: /usr/share/nginx/

    - name: Start nginx service
      ansible.builtin.systemd_service:
        name: nginx
        enabled: true
        state: restarted

